name: "Backup Notion Workspace"

on:
  push:
    branches:
      - main
  schedule:
    -   cron: "0 0 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run backup script
        run: npm install && npm run backup
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_SPACE_ID: ${{ secrets.NOTION_SPACE_ID }}
          NOTION_USER_ID: ${{ secrets.NOTION_USER_ID }}

      - name: Checkout backup repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO_USERNAME }}/${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_PERSONAL_ACCESS_TOKEN }}
          path: "backup-repo"
      
      - name: Commit changes to backup repo
        env:
          REPO_EMAIL: ${{ secrets.REPO_EMAIL }}
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
        run: |
          cp -a workspace/. backup-repo/
          cd backup-repo
          echo "ls"
          ls
          # Find the zip file using the wildcard
          zip_file="$(ls *.zip | head -n1)"
          echo "zip_file" "$zip_file"
          # Unzip the file
          unzip -O utf-8 -q "$zip_file"
          # Get the top-level folder
          folder=$(unzip -Z1 "$zip_file" | awk -F/ '{print $1}' | sort | uniq)
          # Move the contents of the first-level folder to the current directory
          rsync "${folder%/}"/* .
          # Remove the first-level folder
          # echo file
          echo "ls -l"
          ls
          echo "--------------------------------------"
          rm -r "${folder%/}"
          # Delete the zip file
          rm "$zip_file"
          git config --local user.email "${REPO_EMAIL}"
          git config --local user.name "${REPO_USERNAME}"
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          git commit -m "Automated Notion workspace backup"
          git push
